language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
- pypy
install:
- pip install -e .
- pip install -U `python test/fit_requirements.py test/requirements.txt`
- pip install flake8 flake8-import-order pytest-cov coveralls
script:
- | # flake8
  if python -c 'import sys; sys.version_info < (3, 3) or sys.exit(1)'
  then
    EXCLUDE=profiling/remote/asyncio.py
  fi
  flake8 profiling test setup.py -v --show-source --exclude=$EXCLUDE
- | # pytest
  py.test -v --cov=profiling --cov-report=term-missing
after_success:
- coveralls
